DO $$ BEGIN
  CREATE TYPE "OrigemFornecedor" AS ENUM ('MANUAL', 'PNCP');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "StatusCotacaoDireta" ADD VALUE IF NOT EXISTS 'CANCELADA';
ALTER TYPE "StatusCotacaoDireta" ADD VALUE IF NOT EXISTS 'VENCIDA';
ALTER TYPE "StatusCotacaoDireta" ADD VALUE IF NOT EXISTS 'RASCUNHO' BEFORE 'ENVIADA';

ALTER TABLE "Fornecedor"
  ADD COLUMN IF NOT EXISTS "origem" "OrigemFornecedor" NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS "referenciaOrigem" TEXT;

ALTER TABLE "CotacaoDireta"
  ADD COLUMN IF NOT EXISTS "validadeAte" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "observacao" TEXT,
  ADD COLUMN IF NOT EXISTS "dataEnvio" TIMESTAMP(3);

ALTER TABLE "CotacaoDireta" ALTER COLUMN "status" SET DEFAULT 'RASCUNHO';
